package DAO_SERVICE.queries;

public class EHPMQueries {
	public static final String EHPMquery0001 = "SELECT nextEmployeeId FROM next_primary_keys WHERE primaryKey=1;";
	public static final String EHPMquery0002 = "UPDATE next_primary_keys SET nextEmployeeId=? WHERE primaryKey=1;";
//	public static final String EHPMquery0003 = "SELECT customerPrimaryKey FROM next_primary_keys WHERE primaryKey=1;";
	public static final String EHPMquery0004 = "SELECT nextOnlineEmployeeId FROM next_primary_keys WHERE primaryKey=1;";
	public static final String EHPMquery0005 = "UPDATE next_primary_keys SET nextOnlineEmployeeId=? WHERE primaryKey=1;";
	public static final String EHPMquery0006 = "SELECT nextOnlineSecurityId FROM next_primary_keys WHERE primaryKey=1;";
	public static final String EHPMquery0007 = "UPDATE next_primary_keys SET nextOnlineSecurityId=? WHERE primaryKey=1;";
	public static final String EHPMquery0008 = "INSERT INTO online_security_key(onlineSecurityId, onlineSecurityKey) VALUES(?, ?);";
	public static final String EHPMquery0009 = "INSERT INTO online_employee_credentials(onlineEmployeeId, employeeId, username, password) VALUES(?, ?, ?, ?);";
	public static final String EHPMquery0010 = "UPDATE person SET onlineRegistrationDate=?, onlineSecurityId=? WHERE personId=?";
	public static final String EHPMquery0011 = "SELECT * FROM gender;";
	public static final String EHPMquery0012 = "SELECT * FROM nationality;";
//	public static final String EHPMquery0013 = "SELECT * FROM permission;";
	public static final String EHPMquery0014 = "SELECT * FROM branch;";
	public static final String EHPMquery0015 = "SELECT * FROM department;";
	public static final String EHPMquery0016 = "SELECT * FROM designation;";
	public static final String EHPMquery0017 = "SELECT * FROM leave_days;";
	public static final String EHPMquery0018 = "SELECT * FROM leave_details WHERE employeeId=?;";
	public static final String EHPMquery0019 = "SELECT leaveRequestId FROM next_primary_keys WHERE primaryKey=1;";
	public static final String EHPMquery0020 = "UPDATE next_primary_keys SET leaveRequestId=? WHERE primaryKey=1;";
	public static final String EHPMquery0021 = "INSERT INTO leave_request(employeeId, leaveRequestId, leaveType, leaveDescription, leaveRequestedDate, leaveStartDate, leaveDuration, leaveStatus, leaveReviewSpeed) VALUES(?,?,?,?,?,?,?,?, ?);";
	public static final String EHPMquery0022 = "SELECT * FROM leave_request WHERE employeeId=?;";
	public static final String EHPMquery0023 = "SELECT * FROM leave_request WHERE employeeId=? AND leaveStatus=?;";
	public static final String EHPMquery0024 = "INSERT INTO person(personId, firstName, middleName, lastName, otherNames, addressStreet01, addressStreet02, addressCity, addressProvince, addressZipCode, nic, dateOfBirth, personalEmail, physicalRegistrationDate, genderId, nationalityId, branchId, homeContact, mobileContact) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);";
	public static final String EHPMquery0025 = "INSERT INTO employee(employeeId, departmentId, companyEmail, designationId, employeeType) VALUES(?, ?, ?, ?, ?);";
//	public static final String EHPMquery0026 = "INSERT INTO person_contact(personId, contactNumber, type) VALUES(?, ?, ?);";
	public static final String EHPMquery0027 = "INSERT INTO leave_details(employeeId, noOfLeavesLeft, lastEffectiveLeaveDate) VALUES(?, ?, ?);";
	public static final String EHPMquery0028 = "SELECT * FROM person p INNER JOIN employee e ON p.personId = e.employeeId WHERE p.onlineRegistrationDate IS NULL;";
	public static final String EHPMquery0029 = "SELECT * FROM person p INNER JOIN employee e ON p.personId = e.employeeId;";
	public static final String EHPMquery0030 = "SELECT * FROM online_security_key WHERE onlineSecurityId=?";
	public static final String EHPMquery0031 = "SELECT * FROM online_employee_credentials WHERE employeeId=?;";
	public static final String EHPMquery0032 = "DELETE FROM online_employee_credentials WHERE employeeId=?;";
	public static final String EHPMquery0033 = "DELETE FROM online_security_key WHERE onlineSecurityId=?;";
	public static final String EHPMquery0034 = "UPDATE person SET onlineRegistrationDate=NULL WHERE personId=?;";
	public static final String EHPMquery0035 = "DELETE FROM employee WHERE employeeId=?;";
	public static final String EHPMquery0036 = "INSERT INTO inactive_employees(employeeId, reason, inactivationDate) VALUES(?, ?, ?);";
	public static final String EHPMquery0037 = "SELECT * FROM person p INNER JOIN inactive_employees e ON p.personId = e.employeeId;";
	public static final String EHPMquery0038 = "DELETE FROM leave_request WHERE leaveRequestId=?;";
	public static final String EHPMquery0039 = "SELECT * FROM leave_request WHERE leaveStatus='submitted' ORDER BY leaveStartDate;";
	public static final String EHPMquery0040 = "UPDATE leave_request SET leaveStatus=?, leaveReviewedBy=? WHERE leaveRequestId=?;";
	public static final String EHPMquery0041 = "UPDATE leave_details SET noOfLeavesLeft=noOfLeavesLeft-?, lastEffectiveLeaveDate=? WHERE employeeId=?;";
	public static final String EHPMquery0042 = "SELECT password FROM online_employee_credentials WHERE employeeId=?;";
	public static final String EHPMquery0043 = "UPDATE online_employee_credentials SET password=? WHERE employeeId=?;";
	public static final String EHPMquery0044 = "SELECT * FROM employee_update_requests WHERE employeeId=?;";
	public static final String EHPMquery0045 = "INSERT INTO employee_update_requests(employeeId, addressStreet01, addressStreet02, addressCity, addressProvince, addressZipCode) VALUES(?, ?, ?, ?, ?, ?);";
	public static final String EHPMquery0046 = "UPDATE employee_update_requests SET addressStreet01=?, addressStreet02=?, addressCity=?, addressProvince=?, addressZipCode=? WHERE employeeId=?;";
	public static final String EHPMquery0047 = "INSERT INTO employee_update_requests(employeeId, personalEmail) VALUES(?, ?);";
	public static final String EHPMquery0048 = "UPDATE employee_update_requests SET personalEmail=? WHERE employeeId=?;";
	public static final String EHPMquery0049 = "INSERT INTO employee_update_requests(employeeId, homeContact) VALUES(?, ?);";
	public static final String EHPMquery0050 = "UPDATE employee_update_requests SET homeContact=? WHERE employeeId=?;";
	public static final String EHPMquery0051 = "INSERT INTO employee_update_requests(employeeId, mobileContact) VALUES(?, ?);";
	public static final String EHPMquery0052 = "UPDATE employee_update_requests SET mobileContact=? WHERE employeeId=?;";
	public static final String EHPMquery0053 = "SELECT * FROM employee_update_requests;";
	public static final String EHPMquery0054 = "SELECT * FROM person WHERE personId=?;";
	public static final String EHPMquery0055 = "UPDATE person SET addressStreet01=?, addressStreet02=?, addressCity=?, addressProvince=?, addressZipCode=?, personalEmail=?, homeContact=?, mobileContact=? WHERE personId=?;";
	public static final String EHPMquery0056 = "DELETE FROM employee_update_requests WHERE employeeId=?;";
	public static final String EHPMquery0057 = "SELECT * FROM person p INNER JOIN employee e ON p.personId = e.employeeId WHERE personId LIKE ? OR firstName LIKE ? OR middleName LIKE ? OR lastName LIKE ? OR otherNames LIKE ? OR addressStreet01 LIKE ? OR addressStreet02 LIKE ? OR addressCity LIKE ? OR addressProvince LIKE ? OR addressZipCode LIKE ? OR nic LIKE ? OR personalEmail LIKE ? OR branchId LIKE ? OR homeContact LIKE ? OR mobileContact LIKE ? OR departmentId LIKE ? OR companyEmail LIKE ? OR employeeType LIKE ?;";
	public static final String EHPMquery0058 = "SELECT * FROM salary WHERE employeeId=?;";
	public static final String EHPMquery0059 = "INSERT INTO salary(employeeId, basicSalary, otHrs, otRate, carAllowance, bonusPrecentage, taxPercentage, ntSubAllowDays, ntSubAllowRate, ntMedicalAllowance, dEpf, dMedical, dLoanRepayment, dOtherDeductions, totalOT, totalTaxableIncome, totalNonTaxableIncome, totalDeductions, netSalary, approvedBy, date) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);";
	public static final String EHPMquery0060 = "UPDATE salary SET basicSalary=?, otHrs=?, otRate=?, carAllowance=?, bonusPrecentage=?, taxPercentage=?, ntSubAllowDays=?, ntSubAllowRate=?, ntMedicalAllowance=?, dEpf=?, dMedical=?, dLoanRepayment=?, dOtherDeductions=?, totalOT=?, totalTaxableIncome=?, totalNonTaxableIncome=?, totalDeductions=?, netSalary=?, approvedBy=?, date=? WHERE employeeId=?;";
}
